language: ruby
rvm:
  - 2.3.3

script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate RAILS_ENV=test
  - echo "$CODACY_PROJECT_TOKEN"
  - bundle exec rake test
  - ruby -S bundle exec cucumber --profile default

services:
  - postgresql